replicaCount: 1

image:
  repository: "repository-will-be-set-in-ci"  # Подставится из пайплайна
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

postgres:
  password: "vault-managed" # Это просто заглушка
  secretName: "postgres-secret" # Имя, которое создаст ExternalSecrets

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
  className: "nginx" # Должен быть установлен ingress-nginx
  hosts:
    - host: chat.local # Придумываем домен
      paths:
        - path: /
          pathType: Prefix
imagePullSecrets:
- name: gitlab-registry-key