apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # Рекомендуется для безопасности запускать от не-root пользователя
      securityContext:
        fsGroup: 30001
      containers:
      - name: postgres
        image: postgres:15-alpine
        # kube-score требует явного указания PullPolicy
        imagePullPolicy: Always
        # Настройки безопасности контейнера
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 30001
          # Внимание: для Postgres readOnlyRootFilesystem: true 
          # может потребовать доп. настройки временных папок (/tmp, /var/run), 
          # поэтому здесь можно оставить false или настроить emptyDir
          readOnlyRootFilesystem: true 
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret  # Имя секрета, который мы создадим
              key: password         # Ключ внутри секрета
        - name: POSTGRES_DB
          value: "chat_db"
        ports:
        - containerPort: 5432

        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - postgres
              - -d
              - chat_db
          initialDelaySeconds: 5
          periodSeconds: 10

        # Обязательные ресурсы, включая Ephemeral Storage
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
            ephemeral-storage: "100Mi"
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: "1Gi"

        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
        # --- НОВОЕ: монтируем скрипт инициализации ---
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        - name: tmp-dir
          mountPath: /tmp
        - name: run-dir
          mountPath: /var/run/postgresql
      volumes:
      # --- НОВОЕ: связываем с ConfigMap ---
      - name: init-scripts
        configMap:
          name: postgres-init-script
      # ДОБАВЛЯЕМ ПУТИ ДЛЯ ЗАПИСИ
      - name: tmp-dir
        emptyDir: {}
      - name: run-dir
        emptyDir: {}
  
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
