apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
          # Добавляем сюда, чтобы K8s знал, какой ключ использовать для скачивания образа
      imagePullSecrets:
        - name: gitlab-registry-key
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: chat-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        #  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 30001
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: 8080
          env:
            # 1. Берем пароль из секрета (тот же, что у Postgres)
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            
            # 2. Собираем полную строку подключения (DATABASE_URL)
            # Используем имя сервиса 'postgres' как хост
            - name: DATABASE_URL
              value: "postgres://postgres:$(DB_PASSWORD)@postgres:5432/chat_db?sslmode=disable"
          
          # Проверка, что приложение живое
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              httpHeaders:
                - name: X-Probe-Type
                  value: Liveness
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              httpHeaders:
                - name: X-Probe-Type
                  value: Readiness
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: "1Gi"
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: "50Mi"