apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  refreshInterval: "15s" # Как часто проверять обновления в Vault
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret # Имя обычного Secret, который будет создан
    creationPolicy: Owner
  data:
  - secretKey: password # Ключ, который появится в K8s Secret
    remoteRef:
      key: secret/data/chat-app # Путь в Vault (KV engine v2)
      property: password        # Поле внутри секрета в Vault