apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend # имя из вашего SecretStore
    kind: SecretStore
  target:
    name: postgres-k8s-secret # имя секрета, который появится в K8s
    creationPolicy: Owner
  data:
  - secretKey: password  # ключ, который будет в K8s (например, POSTGRES_PASSWORD)
    remoteRef:
      key: secret/chat-app # ПИШЕМ ТАК (без /data/)
      property: password    # название ключа внутри Vault