apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-registry-key
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: gitlab-registry-key
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        # Формируем стандартный конфиг для Docker Auth
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .Values.registry.url | default "registry.gitlab.com" }}": {
                "username": "{{ .user }}",
                "password": "{{ .password }}",
                "auth": "{{ (printf "%s:%s" .user .password) | b64enc }}"
              }
            }
          }
  data:
  - secretKey: user
    remoteRef:
      key: secret/registry
      property: user
  - secretKey: password
    remoteRef:
      key: secret/registry
      property: password